name:
  "wms"
server:
  port: ":8081"

log:
  level: "debug"
  format: "json"
  request: true
  response: true
  request_debug: true

postgresql:
  debugMode: true
  database: "wms_db"
  maxOpenConns: 10
  maxIdleConns: 2
  master:
    host: "localhost"
    port: "5433"  # This matches the mapped port in Docker Compose
    username: "wms_user"
    password: "wms_pass"


